apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: application-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: application-service
    app.kubernetes.io/part-of: application-service
  name: application-service
spec:
  ports:
  - port: 6060
    targetPort: 6060
  selector:
    app.kubernetes.io/instance: application-service
status:
  loadBalancer: {}
