apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: application-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: application-service
    app.kubernetes.io/part-of: application-service
  name: application-servicejlrb
spec:
  port:
    targetPort: 6060
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: application-service
    weight: 100
status: {}
